### ISSUE TITLE
usb tethering not working

### ISSUE THREAD

**Issue by develperbayman** [Joshua-Riek/ubuntu-orange-pi5#1]
simply the usb tethering isnt working

**Comment by develperbayman** [comment]
Yes usually default behavior is automatic on device plug in very important
because orange pi 5 ships without wifi

**Comment by Joshua-Riek** [comment]
I see, I will take a look at this when I have time later today!

**Comment by Joshua-Riek** [comment]
I tested USB tethering out on the Ubuntu 20.04 and 22.04 desktop images in the v1.2 release, and it worked without an issue. I did make some recent changes fixing some wifi and ethernet issues that will be included in the next release, v1.3. I plan on uploading that release sometime tonight or tomorrow. Look out for the v1.3 release and perhaps with the ethernet changes I made, USB tethering will work properly for you.

**Comment by develperbayman** [comment]
yes totally works!
