### ISSUE TITLE
Broken Chromium font

### ISSUE THREAD

**Issue by cantalupo555** [Joshua-Riek/ubuntu-orange-pi5#100]
On some sites like Google Docs and Discord it shows fonts with the wrong color.

![Screenshot from 2023-04-04 10-30-37](https://user-images.githubusercontent.com/12485871/229813631-b87f9423-370f-4e62-ad51-74bb33f4774e.png)

-----

![image](https://user-images.githubusercontent.com/12485871/229813561-ab999d19-a045-47b4-ba7b-a637b01edb8e.png)

-----

![image](https://user-images.githubusercontent.com/12485871/229901269-e0e047ab-8ed9-4faa-babe-0468984648d3.png)

**Comment by Joshua-Riek** [comment]
I do not maintain Chromium, and it still has several issues. We can only wait for updates that improve performance and compatibility.
