### ISSUE TITLE
Overlays

### ISSUE THREAD

**Issue by Gruttebier** [Joshua-Riek/ubuntu-orange-pi5#120]
The overlays=ssd-sata path is changed the code needs the new path. /mnt/overlays.txt

**Comment by Joshua-Riek** [comment]
fstab will mount the boot partition to /boot/firmware. The file should be at /boot/firmware/overlays.txt. 
Could you provide me the output of the lsblk and blkid commands? Maybe the UUID is messed up.

**Comment by Gruttebier** [comment]
Its only the install image. When installed its the right pad.
![Screenshot_2023-04-16_06-06-05](https://user-images.githubusercontent.com/130382515/232255223-d70d498a-0bdf-4414-913b-c05a72562fc8.png)

**Comment by Gruttebier** [comment]
Flash Bootloader to SPI

For a SATA SSD, please use the below comands:

sudo dd if=/usr/share/orangepi/rkspi_loader_sata.img of=/dev/mtdblock0 conv=notrunc 
echo "overlays=ssd-sata" | sudo tee /boot/firmware/overlays.txt

**Comment by Joshua-Riek** [comment]
Do you have the os installed on sda and sdb? The partitions can get messed up due to having the same name. However, I did disable zram in the kernel. Did you enable it yourself?

**Comment by Joshua-Riek** [comment]
I made a few changes in the new release v1.13, and I'm now using the UUID to mount the filesystem at boot time. I have not been able to reproduce this, but using the UUID should help prevent something like this from occurring.
