### ISSUE TITLE
Image does not regenerate machine-id

### ISSUE THREAD

**Issue by td512** [Joshua-Riek/ubuntu-orange-pi5#123]
The image should regenerate both `/etc/machine-id` and `/var/lib/dbus/machine-id` on firstboot to ensure that the system id is unique. This can be done with `rm /etc/machine-id /var/lib/dbus/machine-id && dbus-uuidgen --ensure && systemd-machine-id-setup`

**Comment by Joshua-Riek** [comment]
Interesting, thanks for bringing this to my attention, I might need to have the machine-id generated on the first boot or some of the os images might share the same machine-id. I will do some testing.

**Comment by Joshua-Riek** [comment]
Thanks again for making me aware of this. By default, the file `/etc/machine-id` will now be empty and systemd will automatically generate a random machine-id on the first boot.

**Comment by td512** [comment]
You will likely likely also remove /var/lib/dbus/machine-id since that's where systemd gets its machine-id from

**Comment by Joshua-Riek** [comment]
Yeah, i made sure to remove /var/lib/dbus/machine-id
