### ISSUE TITLE
Can not mount exFat usb stick

### ISSUE THREAD

**Issue by lowelowelowe** [Joshua-Riek/ubuntu-orange-pi5#14]
Can not mount exFat usb stick

got the error 
error mouting unknown filesystem type 'exfat'

i tried
"sudo apt install exfatprogs"
but no luck

**Comment by Joshua-Riek** [comment]
I think I see the issue; the kernel does not have exfat support enabled by default for some reason. I will enable it and give it a try.

**Comment by Joshua-Riek** [comment]
After enabling exfat support in the kernel mounting exfat USB devices now work! This change will be included in the next release. See commit 40088402a7f4c35a7d2cfbecd67c52dbf566abd0.
