### ISSUE TITLE
how to revert original bootloader settings to SDCARD on orange pi 5?

### ISSUE THREAD

**Issue by Lucas-Ed** [Joshua-Riek/ubuntu-orange-pi5#142]
Hello, I'm looking for help, I recently changed the bootloader of my orange pi 5, to the SSD, but I don't know how to revert to the original configuration that is by the SDCARD, I took a look and saw that it has the u-boot file, I don't know if changing the UUID of the unit solves this, but I won't know what the UUID of the SDCARD is either, if you can help me, thank you!

**Comment by Joshua-Riek** [comment]
I don't fully understand. Did you change the files on the sd card's boot partition, and you need to revert them?

**Comment by Lucas-Ed** [comment]
That's right, I'll close the issue, I managed to solve it by flashing the sdcard again, but thanks anyway!
