### ISSUE TITLE
I can't log in to YouTube with the Chromium web browser.

### ISSUE THREAD

**Issue by ironiris** [Joshua-Riek/ubuntu-orange-pi5#15]
In version 1.3, I was able to log in to YouTube with the Chromium web browser, but in version 1.4, I cannot log in.

**Comment by Joshua-Riek** [comment]
Oh, I see the issue. I added --test-type to the chromium start flags in /usr/share/applications/chromium-browser.desktop. Remove that flag and reboot your system, and it should work. But the --no-sandbox warning will appear again.

**Comment by Joshua-Riek** [comment]
To fix for the moment, remove `--test-type` from the file `/usr/share/applications/chromium-browser.desktop` then reboot. 

This does bring back the --no-sandbox warning, but ill deal with that later. See commit 724fd949fcd772469cce54141281501847f0a202.

**Comment by lowelowelowe** [comment]
In version 1.4 I did this

sudo apt update

sudo apt upgrade

wget http://ports.ubuntu.com/ubuntu-ports/pool/universe/c/chromium-browser/chromium-browser_85.0.4183.83-0ubuntu2.22.04.1_arm64.deb

sudo apt install ./chromium-browser_85.0.4183.83-0ubuntu2.22.04.1_arm64.deb

sudo apt install firefox

then chromium browser will able to login to youtube,gmail with out warning

**Comment by Joshua-Riek** [comment]
Yes, that will work, but chromium will no longer be hardware accelerated and use the GPU properly.
