### ISSUE TITLE
Boot from SATA m.2 SSD not NVME

### ISSUE THREAD

**Issue by Ninnix** [Joshua-Riek/ubuntu-orange-pi5#22]
Hi, first of all thank you for the fantastic work you are doing and the support for this device.

I'm trying to boot your ubuntu on SATA ssd NOT nvme. Simply writing the .img 1.6 on Sata SSD with balena the system boot but stuck here:

![PXL_20230221_095719828](https://user-images.githubusercontent.com/17431835/220314260-9b57d8e6-06c7-4056-8ecf-8fdeba932878.jpg)

In general distros do not start directly from this type ssd, at actual state of orange-pi5, the process is well described [here](https://www.reddit.com/r/OrangePI/comments/10iq625/guide_how_to_boot_orange_pi_5_from_sata_m2_ssd/)

I looked inside /boot/ but there are no such files like /boot/orangepiEnv.txt or  /boot/ubuntuEnv.txt

I'm available for further tests.

**Comment by Joshua-Riek** [comment]
Edit the file overlays.txt inside /boot/ to look like `fdt_overlays=rk3588-ssd-sata.dtbo`. I have not tested myself with a SATA SSD but this should work. I need to write up my own guide at some point

**Comment by Ninnix** [comment]
Thanks you for the fast reply.

On sdcard installation I have add to /boot/firmware/overlays.txt `fdt_overlays=rk3588-ssd-sata.dtbo `

after that running `lsblk` I can see Sata SSD and partitions, so

So , I have mount ssd with an clean installation 

sudo mount /dev/sda1 /mnt/

sudo nano /mnt/overlays.txt and add `fdt_overlays=rk3588-ssd-sata.dtbo `

sudo umount /mnt/ && sudo sync

sudo poweroff

Remove SDcard and start again and it boot perfectly, thanks you, all seems okay, but I have random reboot using youtube on chromium, what can be the problem?

**Comment by Joshua-Riek** [comment]
Awesome, glad it works! I have not seen the system reboot when using chromium, there might be a few graphical bugs, but nothing that should cause a system reboot though. Does the system always reboot when using youtube with chromium? Or was this a one-time occurrence?

**Comment by Ninnix** [comment]
Every time same with twitch.tv, hw acceleration is working, but reboot after some, cooling and temp are okay

**Comment by Joshua-Riek** [comment]
Very weird. Maybe the system can't get enough power so it's crashing? Try to remove the SSD and see if this also happens when just using the SD card.

**Comment by Ninnix** [comment]
I have check now, and after 115 minutes bbut with two 1080p video rebooted also on microsd.

this is my charger, its not enough?

![PXL_20230221_163549640](https://user-images.githubusercontent.com/17431835/220407390-5d224d5f-61ce-4259-9f99-6a869a1431ef.jpg)

**Comment by ferrellsl** [comment]
Orange Pi recommends a 5 volt/4 amp power supply.  The one you're using is too weak.

 

    On Tuesday, February 21, 2023 at 09:45:52 AM MST, Ninnix ***@***.***> wrote:  
 
 


I have check now, and after 115 minutes bbut with two 1080p video rebooted also on microsd.

this is my charger, its not enough?

**Comment by Joshua-Riek** [comment]
I just double-checked in the user manual, it does require a 5V/4A power supply.
![image](https://user-images.githubusercontent.com/10427125/220411970-876a4858-ef80-4aff-8559-091a28a9b15e.png)

**Comment by Joshua-Riek** [comment]
I'll be closing this for now, if there are any issues or questions after you get the proper power supply please let me know.
