### ISSUE TITLE
Boot from SD card not working,10minites

### ISSUE THREAD

**Issue by KingingWang** [Joshua-Riek/ubuntu-orange-pi5#25]
Boot from SD card not working,10minites

**Comment by KingingWang** [comment]
I reboot it,it's ok

**Comment by Joshua-Riek** [comment]
I have found that slower SD cards sometimes have an issue on the first boot. Idk if this is the case, but let me know if you encounter this again.

**Comment by KingingWang** [comment]
sorry,I didn't plug the SD card in tight.
