### ISSUE TITLE
CM5 fork?

### ISSUE THREAD

**Issue by samuk** [Joshua-Riek/ubuntu-orange-pi5#31]
I don't know if you'd be interested in maintaining a fork of this project for the upcoming [Radxa CM5? ](https://wiki.radxa.com/Rock5/CM5) It also uses the RK3588S.

I believe https://wiki.radxa.com/Special:SpecialContact are providing early access $free dev kits for those that request them & make a good case, in advance of the main release next month.

**Comment by Joshua-Riek** [comment]
Interesting, Id love to maintain multiple boards, especially since it uses the same RK3588S, so drivers should be similar. But it also depends on the pricing of the hardware if I can't get my hands on a dev kit.

**Comment by samuk** [comment]
Great, It's worth asking for a freebe!
