### ISSUE TITLE
HW acceleration  break by connecting two monitors

### ISSUE THREAD

**Issue by Ninnix** [Joshua-Riek/ubuntu-orange-pi5#32]
Connecting two monitors, one with hdmi and one with usb c the 'hardware acceleration breaks down. unplugging the monitor with usb c makes it work again.

**Comment by Joshua-Riek** [comment]
Interesting, I have not yet tried using usbc for a monitor connection. I will try and see what I can find.

**Comment by Joshua-Riek** [comment]
This is weird wayland seems to crash, and x11 is used. This will require some digging.

**Comment by Ninnix** [comment]
Thanks you for you work and fast answer, if can I help in some Im here.

**Comment by Joshua-Riek** [comment]
I have a usb c adapter that splits into two monitors, which works fine. 
Do you have one monitor plugged into the HDMI port and another into the usb c port?

**Comment by Ninnix** [comment]
Yes its that

**Comment by Joshua-Riek** [comment]
Fixed with commit eee0b78efb6896c0818a11f7adb4b65ce9b11aa6. Thanks for reporting this bug; I would never have found this myself!

**Comment by Ninnix** [comment]
I have test today with 1.8 and still same

**Comment by Joshua-Riek** [comment]
Weird. I will have another try with this.

**Comment by Joshua-Riek** [comment]
Hey, I don't see any issue with the HW acceleration breaking in v1.8 and v1.9. 
Could you provide some more detail on what breaks and what you are doing?
