### ISSUE TITLE
Orangepi-config missing

### ISSUE THREAD

**Issue by dennismongit** [Joshua-Riek/ubuntu-orange-pi5#41]
Hi, (question from a beginner),

I am using the pre-installed Ubuntu 22.04 desktop/server image for the [Orange Pi 5] from your repository which works amazing!
I added an NVME drive and need to switch boot-device in the Orangepi Configuration tool (from SD to NVME).
Maybe/probably it is me, but I can not find this and the command line does not understand the sudo orangepi-config command.

Any suggestions?

**Comment by Joshua-Riek** [comment]
The orangepi-config command does not exist yet.

Booting directly from a USB, NVMe, or SATA device requires flashing U-Boot to the SPI.

### Flash NVMe Bootloader to SPI
```
sudo dd if=/usr/share/orangepi/rkspi_loader.img of=/dev/mtdblock0
```

### Flash SATA Bootloader to SPI
```
sudo dd if=/usr/share/orangepi/rkspi_loader.img of=/dev/mtdblock0
echo "fdt_overlays=rk3588-ssd-sata.dtbo" | sudo tee /boot/firmware/overlays.txt
```

**Comment by dennismongit** [comment]
> The orangepi-config command does not exist as this is not an Armbian-based distro.
> 
> Booting directly from a USB, NVMe, or SATA device requires flashing U-Boot to the SPI. Open a terminal and enter the commands below for your type of SSD:
> 
> ### If using an NVMe SSD
> ```
> sudo dd if=/usr/share/orangepi/rkspi_loader.img of=/dev/mtdblock0
> ```
> 
> ### If using an SATA SSD
> ```
> sudo dd if=/usr/share/orangepi/rkspi_loader.img of=/dev/mtdblock0
> echo "fdt_overlays=rk3588-ssd-sata.dtbo" | sudo tee /boot/firmware/overlays.txt
> ```

Hi Jushua, thanks for the quick reply, tried your suggestion, but unfortunately it results in an error-message (dd: failed to open '/usr/share/orangepi/rkspi_loader': No such file or directory).

I ls-ed the share directory and also can't find any orangepi dir

**Comment by Joshua-Riek** [comment]
Yeah, sorry about that I noticed this issue and have fixed it. You can download the missing files in the zip file attached. [rkspi_loader.zip](https://github.com/Joshua-Riek/ubuntu-orange-pi5/files/10889255/rkspi_loader.zip)

**Comment by Zhu-HH** [comment]
Thank you for providing the ZIP file. I have a question. In September, I downloaded version 1.6 of Ubuntu 20.04 pre installed desktop arm64 range pi5. img. xz. I can find this rkspi_ Loader.img. However, when using this image recently, it was found that the file could not be found.

**Comment by k2m5t2** [comment]
@Joshua-Riek I think it would be great to include the download link for rkspi_loader.zip in the [wiki page for Orange Pi 5](https://github.com/Joshua-Riek/ubuntu-rockchip/wiki/Orange-Pi-5#install-the-bootloader-to-the-spi-nor-flash). Personally, I had to do some hunting to see where this could be found (initally assumed this had to be compiled manually), and it seems like setting up the NVMe as boot source is the pain point for others as well. 

I would be happy to create a PR for this myself but it seems like collborating on Wikis are unexpectedly tricky in GitHub. Btw, thanks for your great work!
