### ISSUE TITLE
Flash U Boot Instructions - directory missing

### ISSUE THREAD

**Issue by atiltman** [Joshua-Riek/ubuntu-orange-pi5#43]
Hi!

The directory **/usr/share/orangepi/** is missing from release 1.7.  

As a result we aren't able to flash the SATA & NVME bootloader's as per the instructions on https://github.com/Joshua-Riek/ubuntu-orange-pi5/wiki/Flash-U-Boot

**Comment by Joshua-Riek** [comment]
I noticed this yesterday and have fixed it with the commit 7a23a47ddc604ab8f5b9bfd5e077308c1829767e. I plan on uploading the next release sometime today with the changes.
