### ISSUE TITLE
An error appears when installing other language packs.

### ISSUE THREAD

**Issue by ironiris** [Joshua-Riek/ubuntu-orange-pi5#5]
It's good to use right now, but to report a bug to make the good OS even better, I don't know if it's the case when adding other languages, but if I add Korean, an error occurs when downloading Thunderbird's Korean language pack.

So I can't apply the language pack, and I have to delete Thunderbird and install the language pack to install successfully.

Thanks for providing a fantastic OS.

**Comment by Joshua-Riek** [comment]
Interesting; I will take a look when I have the time! I'm focusing on a few other bugs, but this is on my list of things to do!

**Comment by ironiris** [comment]
I installed version 1.4 today, and it works fine with no errors.
thank you
