### ISSUE TITLE
I would like to ask, do I have to reinstall the system when I update to version 1.8? 

### ISSUE THREAD

**Issue by KingingWang** [Joshua-Riek/ubuntu-orange-pi5#56]
I would like to ask, do I have to reinstall the system when I update to version 1.8? Or, just use apt update and apt upgrade.

**Comment by Ninnix** [comment]
It would be very cool to be implemented

**Comment by Joshua-Riek** [comment]
I worry about messing up user data, customization could cause unexpected problems i can not foresee. I'm currently reworking some GPU stuff, but after that ill look more into an upgrade process.

**Comment by KingingWang** [comment]
thanks





------------------ Original ------------------
From: Joshua Riek ***@***.***&gt;
Date: Wed,Mar 8,2023 9:39 AM
To: Joshua-Riek/ubuntu-orange-pi5 ***@***.***&gt;
Cc: KingingWang ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [Joshua-Riek/ubuntu-orange-pi5] I would like to ask, do I have toreinstall the system when I update to version 1.8?  (Issue #56)





 
I worry about messing up user data, customization could cause unexpected problems i can not foresee. I'm currently reworking some GPU stuff, but after that ill look more into an upgrade process.
