### ISSUE TITLE
KDE Plasma glitching out

### ISSUE THREAD

**Issue by ByteAtATime** [Joshua-Riek/ubuntu-orange-pi5#70]
First of all, thanks for making this! However, when I tried to install KDE Plasma on this, it didn't launch at all with SDDM (It just froze up after I entered the password) and with GDM (from Gnome) it launches with a bunch of weird artifacts. Not sure if this is KDE Plasma's problem or anything, but just thought I could get some support. Thanks!

**Comment by Joshua-Riek** [comment]
I'm trying not to officially support any desktop environment with x11 as a display manager. There are a lot of issues with the GPU / hardware acceleration under the x11 display manager. 

However, wayland, as a display manager, works excellently. But the only mature desktop environment that uses wayland is GNOME. KDE has a wayland version, but it seems like a buggy mess.

I might work on a version of Ubuntu that has some support for x11 based desktop environments. But the performance would be poor, and there could be quite a number of bugs.
