### ISSUE TITLE
Wifi connectivity.

### ISSUE THREAD

**Issue by Akira2i** [Joshua-Riek/ubuntu-orange-pi5#78]
I've attached an m.2 to e key adapter to use an Intel wifi module ax210ngw. The driver and device is detected but there is no wifi tab in the networks tab. Thanks for the help. Newest image being used.

**Comment by Joshua-Riek** [comment]
Hey! I have this wifi module coming in sometime today, and will be able to look into this further once it arrives!

**Comment by Joshua-Riek** [comment]
There is a [well-documented](https://askubuntu.com/questions/1360175/intel-wifi-6-ax210-wifi-not-working-after-update) issue where updating the `linux-firmware` package will break wifi on this device. This is not something I can fix, but I can make sure this wifi module works out of the box before a user updates the `linux-firmware` package, if it even has an update available.

If the wifi module stops working after an update, enter the below command:
```
sudo mv /usr/lib/firmware/iwlwifi-ty-a0-gf-a0.pnvm  /usr/lib/firmware/iwlwifi-ty-a0-gf-a0.bak
```

**Comment by Joshua-Riek** [comment]
I added commit 1e97a41a696ee91dd214f785fc1f3932261cf7b0 to enable wifi for this device right out of the box. It can still break if the linux-firmware package is updated. I don't see any fix for this besides updating to a more recent kernel version, but the only supported kernel version is 5.10.110 for this device.
