### ISSUE TITLE
SSH login fails

### ISSUE THREAD

**Issue by rahul-kurup** [Joshua-Riek/ubuntu-orange-pi5#82]
Using latest build v1.10

I've tried both `root` and `ubuntu` users with password `ubuntu`. But its failing:

![image](https://user-images.githubusercontent.com/29568606/226651557-07227717-3dc7-4c27-aa1e-1180dff0e169.png)

**Comment by Joshua-Riek** [comment]
Using the server or desktop image?

**Comment by rahul-kurup** [comment]
server

**Comment by Joshua-Riek** [comment]
Got it, taking a look now.

**Comment by Joshua-Riek** [comment]
Weird, ssh login fails on my side too. I think its an issue with cloud-init

**Comment by rahul-kurup** [comment]
I was about to flash desktop version, was waiting for your reply. You may close this ticket and test it at a later period of time

**Comment by Joshua-Riek** [comment]
Thanks for reporting this issue! I forgot to update the fs label for cloud-init, and it has been fixed with commit dde33ec485de22d042fcd615770f6fb2b848a750. I'll start a build on my server and update the release in a few hours.

**Comment by artem-zinnatullin** [comment]
Huh, actually ssh with `ubuntu` user and `ubuntu` password worked! But ssh with `root` user doesn't :)

**Comment by Joshua-Riek** [comment]
root login through ssh is disabled by default for security reasons.
