### ISSUE TITLE
How to update an OS

### ISSUE THREAD

**Issue by Singular112** [Joshua-Riek/ubuntu-orange-pi5#83]
Hi. How to update an OS that was already burned to the SD card instead of a new install ?

New versions releasing frequently and it is impossible to reinstall the system every time and configure everything from scratch.

**Comment by Joshua-Riek** [comment]
I have had a lot of people asking the same question, and creating an update process will be the next thing I do. The process will include updating the kernel, bootloader, firmware, and packages. This will contain most changes between versions, I will need to do a lot of testing to get this right.

**Comment by stuartcamerondeakin** [comment]
It's still early days, I'd honestly rather you spend your time on anything that's still likely to yield big improvements to the system, incremental updates are going to more useful once there's less of a tinkerer-focused and more stable branch focused audience.

**Comment by Joshua-Riek** [comment]
You make a great point, I have multiple improvements in the works, and it's difficult to keep up with the rapidly developing changes around this board when long-term stability and updates are in mind. Thank you for the feedback.

**Comment by Joshua-Riek** [comment]
I have a small update. I made some mirrors of liujianfeng1994's PPAs, which contain multiple packages related to hardware acceleration. This will allow me to test changes made to liujianfeng1994's PPA before updating my mirror and distributing those changes to users. However, I will need some time to implement it properly, I need to re-work how I implement hardware acceleration and make sure it does not produce any new issues.

**Comment by stuartcamerondeakin** [comment]
Sounds awesome, appreciate the time you're putting into this!

**Comment by Joshua-Riek** [comment]
All mesa and multimedia-related packages are now available through a PPA with the commit 54325f4031900933dfacffe9be4807698488a57d. I will clean up the commit later when I have time. I will be working on packaging the kernel, bootloader, and firmware at a later date now that I have a process in place for distributing packages.

**Comment by Joshua-Riek** [comment]
I'm happy to say the kernel and firmware are fully packaged now on my PPA. I need to add the bootloader and a few more packages, but distributing package updates should be as simple as an apt upgrade in the next release. 

https://launchpad.net/~jjriek/+archive/ubuntu/orangepi5/+packages

**Comment by ferrellsl** [comment]
> I'm happy to say the kernel and firmware are fully packaged now on my PPA. I need to add the bootloader and a few more packages, but distributing package updates should be as simple as an apt upgrade in the next release.
> 
> https://launchpad.net/~jjriek/+archive/ubuntu/orangepi5/+packages

Does this mean that if I'm running release v1.11 that I can now upgrade to v1.12 by doing a sudo apt update followed by a sudo apt upgrade?

**Comment by Joshua-Riek** [comment]
I'm not sure about that yet. I've had to change a few essential boot files for the update process to work.

**Comment by Joshua-Riek** [comment]
I'm happy to announce that [v1.13](https://github.com/Joshua-Riek/ubuntu-orange-pi5/releases/tag/v1.13) is now released, and users will be able to receive kernel, firmware, and bootloader updates through apt. However, this is not compatible with any previous release.

**Comment by tanmaster** [comment]
>I'm happy to announce that [v1.13](https://github.com/Joshua-Riek/ubuntu-orange-pi5/releases/tag/v1.13) is now released, and users will be able to receive kernel, firmware, and bootloader updates through apt. However, this is not compatible with any previous release.

thank you for your work, this is great!
