### ISSUE TITLE
Netflix logging out

### ISSUE THREAD

**Issue by cantalupo555** [Joshua-Riek/ubuntu-orange-pi5#99]
Whenever I start some content it logs out, directs the page to:
https://www.netflix.com/clearcookies

Sometimes it presents these errors and tries to log out:
UI3012
M7121-1331
M7701-1003

All other streaming works perfectly in Chromium.

**Comment by ironiris** [comment]
Have you changed the string of the user-agent?

**Comment by cantalupo555** [comment]
> Have you changed the string of the user-agent?

No, clean installation of the system.
No changes were made.

**Comment by rahul-kurup** [comment]
@cantalupo555 Netflix will keep on logging out, **unless you change your user agent to Chrome OS while browsing**. 
Something like this should work for you:

- Install [User-Agent Switcher](https://chrome.google.com/webstore/detail/user-agent-switcher-for-c/djflhoibgkdhkhhcedjiklpkjnoahfmg) extension
- Get latest [ChromeOS user agent](https://www.whatismybrowser.com/guides/the-latest-user-agent/chrome-os); use **Aarch64 on Chrome OS** and set it up in this extension.
- Switch to the above user agent.
- Now navigate to https://netflix.com. Login and watch whatever you want.
- Bonus: Install [Netflix1080p](https://chrome.google.com/webstore/detail/netflix-1080p/cankofcoohmbhfpcemhmaaeennfbnmgp) extension for better viewing experience. Check all the options shown in the extension settings

**Comment by Joshua-Riek** [comment]
I will probably add this in the next few days. I have been very busy with my job and planning for future changes.

**Comment by Big-BenG** [comment]
How can I get the latest ChromeOS user agent ? Many thanks

**Comment by Big-BenG** [comment]
THX

**Comment by cantalupo555** [comment]
@rahul-kurup 
![image](https://user-images.githubusercontent.com/12485871/229618077-5cbddaf7-c7a4-4eb3-922f-f02fd3a1e1f6.png)

Where do I configure the extension?

![image](https://user-images.githubusercontent.com/12485871/229618375-092fbf31-e5b5-494c-a500-344ecf3b0761.png)

**Comment by cantalupo555** [comment]
Got it!

![image](https://user-images.githubusercontent.com/12485871/229619432-f32de4c9-9333-403d-9fea-1a501525460f.png)

![Screenshot from 2023-04-03 17-21-31](https://user-images.githubusercontent.com/12485871/229619631-ded043ae-9759-4628-95c1-2c3c8017fb24.png)
